name: Salesforce Code Analyzer Workflow
on: workflow_dispatch
jobs:
  salesforce-code-analyzer-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html
          results-artifact-name: salesforce-code-analyzer-results

      - name: Get Access Token
        id: get_token
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ vars.SF_ORG_URL }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"grant_type":"client_credentials", "client_id": "${{ secrets.SF_CLIENT_ID }}", "client_secret":"${{ secrets.SF_CLIENT_SECRET }}"}'

      - name: Notify Execution completion
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ vars.SF_ORG_URL }}/services/data/v60.0/sobjects/sf_devops__Test_Execution_Completed__e/'
          customHeaders: '{"Content-Type": "application/json","Authorization":"bearer ${{ steps.get_token.outputs.response.access_token }}"}'
          data: '{"sf_devops__executionId__c": "MTSE-00001","sf_devops__message__c": "Code Analyser tests execution completed","sf_devops__Test_Provider__c": "Salesforce Code Analyser"}'
    
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
